version: "3.9"

services:
  datasource:
    build:
      context: .
      dockerfile: DB.Dockerfile
    ports:
    - "1433:1433"
    hostname: cfa-datasource
    restart: always

  api:
    depends_on:
      - reverse_proxy
      - datasource
    build:
      context: .
      dockerfile: Api.Dockerfile
    ports:
      - "8080:80"
    hostname: cfa-api
    restart: always
